### ISSUE TITLE
# do_connect()

### ISSUE THREAD

**Issue by winner69** [Nkawu/coffee-scale-firmware#3]
Sorry to bother you again. i'm a newbie

Which line should I comment? . " # do_connect() "

as below I'm correct?

Thank you.

-- # access point interface is enabled by default
18 def disable_ap():
19 ap_if = network.WLAN(network.AP_IF)
20 if ap_if.active():
21 ap_if.active(False)
22
23 esp.osdebug(None)
24 disable_ap()
-add- # do_connect()      <<<<<< 
25 # connect_sta()

**Comment by Nkawu** [comment]
I changed the `boot.py` script to make it clear:

```python
import network
import esp

# station interface is not active by default
def connect_sta():
    sta_if = network.WLAN(network.STA_IF)
    sta_if.active(True)
    if not sta_if.isconnected():
        print('Connecting to network...')
        # Enter WiFi parameters here
        sta_if.connect('*SSID*', '*PASSWORD*')
        while not sta_if.isconnected():
            pass
    print('Network config:', sta_if.ifconfig())

# access point interface is enabled by default
def disable_ap():
    ap_if = network.WLAN(network.AP_IF)
    if ap_if.active():
        ap_if.active(False)

esp.osdebug(None)
disable_ap()

# Uncomment the following line to setup WiFi connection
# connect_sta()
```
You will notice that `connect_sta()` is commented out by default, so you should not have to do anything

**Comment by winner69** [comment]
Thank you.
