### ISSUE TITLE
BAT STATUS

### ISSUE THREAD

**Issue by winner69** [Nkawu/coffee-scale-firmware#4]
Hi,
1. how can I activate this pin? (BAT_SWITCH_PIN enables/disables) Is 3v connected to this pin? 
2. what resistor value are you using ?

**Comment by Nkawu** [comment]
1. The BAT_SWITCH_PIN is an internal switch on the board, just setting the pin high/low turns on the ability to measure voltage on the board. Look at **Cell Voltage Measurement** in [ESP32 In Feather Format](https://news.ezsbc.com/esp32-in-feather-format/)
2. I will have to open my scale to confirm, but I believe the board I used already contains a voltage divider
